on:
  push:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7.4
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
      - name: Install React app dependencies
        run: |
          cd client
          npm install
     
